import { BossConfig, BossType } from './types';

export const BOSS_CONFIGS: Record<BossType, BossConfig> = {
  [BossType.BigDemon]: {
    type: BossType.BigDemon,
    name: 'THE DEMON LORD',
    spriteKey: 'big_demon',
    hp: 80,
    phases: 2,
    phase2Tint: 0xff4400,
    scale: 2.0,
    hasRunAnim: true,
    speed: 45,
    damage: 2,
    projectileColor: 0xff4400,
    attackCooldownMs: 1800,
  },
  [BossType.DarkKnight]: {
    type: BossType.DarkKnight,
    name: 'THE DARK KNIGHT',
    spriteKey: 'monster_dark_knight',
    hp: 130,
    phases: 2,
    phase2Tint: 0x0055ff,
    scale: 2.2,
    hasRunAnim: false,
    speed: 38,
    damage: 3,
    projectileColor: 0x4466ff,
    attackCooldownMs: 1500,
  },
  [BossType.Necromancer]: {
    type: BossType.Necromancer,
    name: 'THE NECROMANCER',
    spriteKey: 'necromancer',
    hp: 170,
    phases: 3,
    phase2Tint: 0x8800ff,
    scale: 1.8,
    hasRunAnim: true,
    speed: 35,
    damage: 3,
    projectileColor: 0x8800ff,
    attackCooldownMs: 2000,
  },
  [BossType.ElementalFusion]: {
    type: BossType.ElementalFusion,
    name: 'ELEMENTAL FUSION',
    spriteKey: 'monster_elemental_fire',
    hp: 220,
    phases: 3,
    phase2Tint: 0x00ffaa,
    scale: 2.5,
    hasRunAnim: false,
    speed: 42,
    damage: 4,
    projectileColor: 0x00ffaa,
    attackCooldownMs: 1200,
  },
  [BossType.TheWatcher]: {
    type: BossType.TheWatcher,
    name: 'THE WATCHER',
    spriteKey: 'monster_demonolog',
    hp: 320,
    phases: 3,
    phase2Tint: 0xcc33ff,
    scale: 2.2,
    hasRunAnim: false,
    speed: 48,
    damage: 5,
    projectileColor: 0xcc33ff,
    attackCooldownMs: 1000,
  },
};
