import { EnemyBehavior, EnemyConfig, EnemyType } from './types';

export const ENEMY_CONFIGS: Record<EnemyType, EnemyConfig> = {
  [EnemyType.Goblin]: {
    type: EnemyType.Goblin,
    spriteKey: 'goblin',
    hp: 4,
    speed: 58,
    damage: 1,
    xp: 5,
    behavior: EnemyBehavior.MeleeChase,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'goblin_attack',
  },
  [EnemyType.Imp]: {
    type: EnemyType.Imp,
    spriteKey: 'imp',
    hp: 3,
    speed: 75,
    damage: 1,
    xp: 6,
    behavior: EnemyBehavior.RangedShoot,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'elemental_magic',
  },
  [EnemyType.Chort]: {
    type: EnemyType.Chort,
    spriteKey: 'chort',
    hp: 6,
    speed: 68,
    damage: 2,
    xp: 9,
    behavior: EnemyBehavior.MeleeChase,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'goblin_attack',
  },
  [EnemyType.BigZombie]: {
    type: EnemyType.BigZombie,
    spriteKey: 'big_zombie',
    hp: 14,
    speed: 38,
    damage: 3,
    xp: 16,
    behavior: EnemyBehavior.MeleeChase,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'zombie_growl',
  },
  [EnemyType.IceZombie]: {
    type: EnemyType.IceZombie,
    spriteKey: 'ice_zombie',
    hp: 8,
    speed: 30,
    damage: 2,
    xp: 13,
    behavior: EnemyBehavior.Exploder,
    scale: 1.0,
    hasRunAnim: false,
    projectileColor: 0xffcc00,
    attackSfx: 'zombie_growl',
  },
  [EnemyType.MaskedOrc]: {
    type: EnemyType.MaskedOrc,
    spriteKey: 'masked_orc',
    hp: 16,
    speed: 52,
    damage: 4,
    xp: 22,
    behavior: EnemyBehavior.Shielded,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'orc_roar',
  },
  [EnemyType.BigDemon]: {
    type: EnemyType.BigDemon,
    spriteKey: 'big_demon',
    hp: 22,
    speed: 48,
    damage: 5,
    xp: 32,
    behavior: EnemyBehavior.RangedShoot,
    scale: 1.2,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'orc_roar',
  },
  [EnemyType.Skelet]: {
    type: EnemyType.Skelet,
    spriteKey: 'skelet',
    hp: 6,
    speed: 62,
    damage: 2,
    xp: 11,
    behavior: EnemyBehavior.SplitOnDeath,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'skeleton_rattle',
  },
  [EnemyType.Necromancer]: {
    type: EnemyType.Necromancer,
    spriteKey: 'necromancer',
    hp: 20,
    speed: 42,
    damage: 3,
    xp: 28,
    behavior: EnemyBehavior.Summoner,
    scale: 1.0,
    hasRunAnim: true,
    projectileColor: 0xffcc00,
    attackSfx: 'elemental_magic',
  },
  [EnemyType.OrcArmored]: {
    type: EnemyType.OrcArmored,
    spriteKey: 'orc_armored',
    hp: 28,
    speed: 44,
    damage: 5,
    xp: 38,
    behavior: EnemyBehavior.Shielded,
    scale: 1.1,
    hasRunAnim: false,
    projectileColor: 0xffcc00,
    attackSfx: 'orc_roar',
  },
};

export const ENEMY_LEVEL_POOLS: Record<number, EnemyType[]> = {
  1: [EnemyType.Goblin, EnemyType.Imp],
  2: [EnemyType.Goblin, EnemyType.Imp, EnemyType.Chort, EnemyType.BigZombie],
  3: [EnemyType.Chort, EnemyType.BigZombie, EnemyType.Skelet, EnemyType.IceZombie],
  4: [EnemyType.Skelet, EnemyType.MaskedOrc, EnemyType.BigZombie, EnemyType.BigDemon],
  5: [EnemyType.Necromancer, EnemyType.MaskedOrc, EnemyType.BigDemon, EnemyType.OrcArmored],
};
