import { ItemConfig, ItemEffect, ItemRarity, ItemType } from './types';

export const ITEM_CONFIGS: Record<ItemType, ItemConfig> = {
  [ItemType.WeaponSword]: {
    type: ItemType.WeaponSword,
    name: 'Sword',
    sprite: 'weapon_regular_sword',
    effect: ItemEffect.BoostDamage,
    value: 1,
    rarity: ItemRarity.Common,
  },
  [ItemType.WeaponDagger]: {
    type: ItemType.WeaponDagger,
    name: 'NINJA THROWER',
    sprite: 'weapon_shuriken',
    effect: ItemEffect.BoostDamage,
    value: 1,
    rarity: ItemRarity.Common,
  },
  [ItemType.WeaponKatana]: {
    type: ItemType.WeaponKatana,
    name: 'Katana',
    sprite: 'weapon_katana',
    effect: ItemEffect.BoostDamage,
    value: 3,
    rarity: ItemRarity.Rare,
  },
  [ItemType.WeaponHammer]: {
    type: ItemType.WeaponHammer,
    name: 'War Hammer',
    sprite: 'weapon_big_hammer',
    effect: ItemEffect.BoostDamage,
    value: 2,
    rarity: ItemRarity.Uncommon,
  },
  [ItemType.WeaponBomb]: {
    type: ItemType.WeaponBomb,
    name: 'Pixel Bomb',
    sprite: 'bomb_f0',
    effect: ItemEffect.BoostDamage,
    value: 4,
    rarity: ItemRarity.Uncommon,
  },
  [ItemType.FlaskRed]: {
    type: ItemType.FlaskRed,
    name: 'Health Potion',
    sprite: 'flask_red',
    effect: ItemEffect.HealHP,
    value: 2,
    rarity: ItemRarity.Common,
  },
  [ItemType.FlaskBlue]: {
    type: ItemType.FlaskBlue,
    name: 'Speed Potion',
    sprite: 'flask_blue',
    effect: ItemEffect.BoostSpeed,
    value: 1.5,
    rarity: ItemRarity.Common,
    duration: 5000,
  },
  [ItemType.FlaskGreen]: {
    type: ItemType.FlaskGreen,
    name: 'Shield Potion',
    sprite: 'flask_green',
    effect: ItemEffect.Shield,
    value: 1,
    rarity: ItemRarity.Uncommon,
    duration: 8000,
  },
  [ItemType.FlaskYellow]: {
    type: ItemType.FlaskYellow,
    name: 'Rage Potion',
    sprite: 'flask_yellow',
    effect: ItemEffect.BoostDamage,
    value: 2,
    rarity: ItemRarity.Uncommon,
    duration: 6000,
  },
  [ItemType.FlaskBigRed]: {
    type: ItemType.FlaskBigRed,
    name: 'Greater Health',
    sprite: 'flask_big_red',
    effect: ItemEffect.HealHP,
    value: 3,
    rarity: ItemRarity.Rare,
  },
  [ItemType.FlaskBigBlue]: {
    type: ItemType.FlaskBigBlue,
    name: 'Greater Speed',
    sprite: 'flask_big_blue',
    effect: ItemEffect.BoostSpeed,
    value: 2.0,
    rarity: ItemRarity.Rare,
    duration: 10000,
  },
  [ItemType.PoisonVial]: {
    type: ItemType.PoisonVial,
    name: 'Poison Vial',
    sprite: 'flask_big_green',
    effect: ItemEffect.RestoreDash,
    value: 1,
    rarity: ItemRarity.Uncommon,
  },
  [ItemType.Coin]: {
    type: ItemType.Coin,
    name: 'Gold Coin',
    sprite: 'coin_anim_f0',
    effect: ItemEffect.AddCoins,
    value: 1,
    rarity: ItemRarity.Common,
  },
  [ItemType.Chest]: {
    type: ItemType.Chest,
    name: 'Chest',
    sprite: 'chest_closed',
    effect: ItemEffect.AddCoins,
    value: 10,
    rarity: ItemRarity.Common,
  },
  [ItemType.GoldenChest]: {
    type: ItemType.GoldenChest,
    name: 'Golden Chest',
    sprite: 'chest_golden_closed',
    effect: ItemEffect.AddCoins,
    value: 30,
    rarity: ItemRarity.Rare,
  },
};

export const WEAPON_ORDER: ItemType[] = [
  ItemType.WeaponSword,
  ItemType.WeaponDagger,
  ItemType.WeaponKatana,
  ItemType.WeaponHammer,
  ItemType.WeaponBomb,
];

export const WEAPON_LABELS: Record<ItemType, string> = {
  [ItemType.WeaponSword]: 'SWORD',
  [ItemType.WeaponDagger]: 'NINJA THROWER',
  [ItemType.WeaponKatana]: 'KATANA',
  [ItemType.WeaponHammer]: 'HAMMER',
  [ItemType.WeaponBomb]: 'PIXEL BOMB',
  [ItemType.FlaskRed]: 'FLASK',
  [ItemType.FlaskBlue]: 'FLASK',
  [ItemType.FlaskGreen]: 'FLASK',
  [ItemType.FlaskYellow]: 'FLASK',
  [ItemType.FlaskBigRed]: 'FLASK',
  [ItemType.FlaskBigBlue]: 'FLASK',
  [ItemType.PoisonVial]: 'POISON',
  [ItemType.Coin]: 'COIN',
  [ItemType.Chest]: 'CHEST',
  [ItemType.GoldenChest]: 'CHEST',
};
