import { ItemType, WeaponConfig } from './types';

export const WEAPON_CONFIGS: Record<ItemType, WeaponConfig> = {
  [ItemType.WeaponSword]: {
    damageMult: 1.0,
    fireRateMult: 1.0,
    projectileCount: 1,
    spreadDeg: 0,
    projectileSpeed: 260,
    knockback: 85,
    projectileKey: 'weapon_sword_slash',
    projectileScale: 1,
    projectileSpinDegPerSec: 0,
    projectileRotationOffset: Math.PI / 2,
    muzzleFlashColor: 0x66ccff,
    muzzleFlashSize: 7,
    shakeIntensity: 0.002,
    holdOffset: { x: 0, y: 3 },
    rotationOffset: Math.PI / 2,
    weaponScale: 1,
  },
  [ItemType.WeaponDagger]: {
    damageMult: 0.7,
    fireRateMult: 1.4,
    projectileCount: 1,
    spreadDeg: 0,
    projectileSpeed: 380,
    knockback: 70,
    projectileKey: 'weapon_shuriken',
    projectileScale: 0.45,
    projectileSpinDegPerSec: 520,
    projectileRotationOffset: 0,
    muzzleFlashColor: 0xfaf089,
    muzzleFlashSize: 5,
    shakeIntensity: 0.0016,
    holdOffset: { x: 1, y: 2 },
    rotationOffset: Math.PI / 3,
    weaponScale: 0.9,
    critChance: 0.1,
  },
  [ItemType.WeaponKatana]: {
    damageMult: 1.6,
    fireRateMult: 0.9,
    projectileCount: 1,
    spreadDeg: 0,
    projectileSpeed: 300,
    knockback: 95,
    projectileKey: 'weapon_katana',
    projectileScale: 0.65,
    projectileSpinDegPerSec: 180,
    projectileRotationOffset: Math.PI / 2,
    muzzleFlashColor: 0xff5555,
    muzzleFlashSize: 9,
    shakeIntensity: 0.0025,
    holdOffset: { x: -1, y: 4 },
    rotationOffset: Math.PI / 2,
    weaponScale: 1.05,
    pierce: 1,
  },
  [ItemType.WeaponHammer]: {
    damageMult: 2.2,
    fireRateMult: 0.6,
    projectileCount: 1,
    spreadDeg: 0,
    projectileSpeed: 210,
    knockback: 140,
    projectileKey: 'weapon_big_hammer',
    projectileScale: 0.8,
    projectileSpinDegPerSec: 120,
    projectileRotationOffset: Math.PI / 2,
    muzzleFlashColor: 0xffaa55,
    muzzleFlashSize: 11,
    shakeIntensity: 0.0035,
    holdOffset: { x: -2, y: 4 },
    rotationOffset: Math.PI / 2,
    weaponScale: 1.15,
  },
  [ItemType.WeaponBomb]: {
    damageMult: 2.8,
    fireRateMult: 0.5,
    projectileCount: 1,
    spreadDeg: 0,
    projectileSpeed: 180,
    knockback: 60,
    projectileKey: 'bomb_f0',
    projectileScale: 0.8,
    projectileSpinDegPerSec: 0,
    projectileRotationOffset: 0,
    muzzleFlashColor: 0x99ff99,
    muzzleFlashSize: 10,
    shakeIntensity: 0.004,
    holdOffset: { x: 0, y: 2 },
    rotationOffset: 0,
    weaponScale: 1.05,
    explosion: {
      radius: 64,
      fuseMs: 900,
      flashColor: 0xaaffcc,
      shake: 0.006,
    },
    holdAnimationKey: 'bomb_fuse',
  },
};
