import { BossType, EnemyType, LevelData } from '../config/types';

export const LEVELS: LevelData[] = [
  {
    level: 1,
    name: 'THE DUNGEON ENTRANCE',
    subtitle: 'Something stirs in the darkness…',
    mapW: 40,
    mapH: 40,
    roomCount: 8,
    enemyCount: 10,
    bossType: BossType.BigDemon,
    enemyHPMult: 1.0,
    enemySpdMult: 1.0,
    fogDensity: 0.55,
    bgColor: 0x0a0a1a,
    ambientColor: 0x000000,
    enemyTypes: [EnemyType.Goblin, EnemyType.Imp],
  },
  {
    level: 2,
    name: 'THE DARK CORRIDORS',
    subtitle: 'Iron boots echo in the black halls.',
    mapW: 60,
    mapH: 60,
    roomCount: 14,
    enemyCount: 20,
    bossType: BossType.DarkKnight,
    enemyHPMult: 1.3,
    enemySpdMult: 1.1,
    fogDensity: 0.62,
    bgColor: 0x0c0a18,
    ambientColor: 0x000000,
    enemyTypes: [EnemyType.Goblin, EnemyType.Imp, EnemyType.Chort, EnemyType.BigZombie],
  },
  {
    level: 3,
    name: 'THE CRYPT',
    subtitle: 'The dead do not rest here.',
    mapW: 80,
    mapH: 80,
    roomCount: 20,
    enemyCount: 32,
    bossType: BossType.Necromancer,
    enemyHPMult: 1.6,
    enemySpdMult: 1.2,
    fogDensity: 0.7,
    bgColor: 0x080c18,
    ambientColor: 0x000000,
    enemyTypes: [EnemyType.Chort, EnemyType.BigZombie, EnemyType.Skelet, EnemyType.IceZombie],
  },
  {
    level: 4,
    name: 'THE ELEMENTAL FORGE',
    subtitle: 'Heat. Cold. Thunder. Void.',
    mapW: 100,
    mapH: 100,
    roomCount: 28,
    enemyCount: 48,
    bossType: BossType.ElementalFusion,
    enemyHPMult: 2.0,
    enemySpdMult: 1.4,
    fogDensity: 0.75,
    bgColor: 0x0a1208,
    ambientColor: 0x000000,
    enemyTypes: [EnemyType.Skelet, EnemyType.MaskedOrc, EnemyType.BigZombie, EnemyType.BigDemon],
  },
  {
    level: 5,
    name: 'THE ABYSS',
    subtitle: 'It has been watching you the whole time.',
    mapW: 120,
    mapH: 120,
    roomCount: 38,
    enemyCount: 65,
    bossType: BossType.TheWatcher,
    enemyHPMult: 2.5,
    enemySpdMult: 1.6,
    fogDensity: 0.85,
    bgColor: 0x020008,
    ambientColor: 0x000000,
    enemyTypes: [EnemyType.Necromancer, EnemyType.MaskedOrc, EnemyType.BigDemon, EnemyType.OrcArmored],
  },
];

export const getLevelData = (level: number): LevelData => {
  const clamped = Math.max(1, Math.min(LEVELS.length, level));
  return LEVELS[clamped - 1];
};
